Updated FIR TDM examples
Xilinx/Vitis_Model_Composer pull request #62
Opened 2024-12-04 11:57 UTC by SrilakshmiDegala

2024-12-04 15:11 UTC, robgraessle approved these changes

2024-12-04 19:43 UTC, abehbood requested changes

2024-12-04 19:43 UTC, abehbood commented on Examples/Block_Help/AIE/FIR_TDM_Ex1/FIR_TDM_Ex1.slx
Here are my input for this design:

* In the merging subsystem, remove the terminal block and remove the valid port. This is a better practice. User should not simply stick a terminal to the valid port and not realize they are seeing invalid data. 
* Replace the name of the splitter block to round_robin for better clarity. 
* The note applies to a block with one input and one output. It does not apply for an SSR block. Perhaps change to read "The input to the round_robin block ..."
* Make the number of channels and the number of filter coefficients to be different. Right now they are both 16. Different values adds more clarity. 
* When I change the number of filter coeffs to be 32, things don't work anymore. Why?

2024-12-04 19:43 UTC, abehbood commented on Examples/Block_Help/AIE/FIR_TDM_Ex2/FIR_TDM_Ex2.slx
All the inputs for the previous model applies to this model as well.

2024-12-05 16:00 UTC, abehbood approved these changes
Thank you @SrilakshmiDegala . I reviewed the changes and they look good.

2024-12-05 18:10 UTC, merged